# Generated by Django 4.2 on 2023-04-30 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adres', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Treners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, verbose_name='Имя тренера')),
                ('last_name', models.CharField(blank=True, max_length=200, verbose_name='Фамилия тренера')),
                ('phone', models.CharField(blank=True, max_length=200, verbose_name='Телефон тренера')),
                ('mail', models.CharField(blank=True, max_length=200, verbose_name='Майл тренера')),
            ],
        ),
        migrations.CreateModel(
            name='Trenings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jim_main.halls')),
                ('trener', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jim_main.treners')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Abonements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('countTrenagers', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
