# Generated by Django 4.2 on 2023-05-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jim_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treners',
            name='photos',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
